//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessOsnova_Kam_Dav.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        public int BookingID { get; set; }
        public int ClientID { get; set; }
        public int TrainingID { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public string Status { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Trainings Trainings { get; set; }
    }
}
